### ISSUE TITLE
icacls cannot run from any other directory than system32...

### ISSUE THREAD

**Issue by RyokoAsakura** [Selanda/UpdateOrch-AntiAutoReboot#1]
You should hard-code the path for ICACLS to C:\Windows\System32\ because it fails when run from any other location, regardless of user GUID/escalation.

**Comment by Selanda** [comment]
Reordered steps for more logical progression. Added extra pause at the end to ensure the user read and completed Step 4 before exiting. Fully pathed icacls.exe per request by @RyokoAsakura  . Version 1.2 released to satisfy bug.
